"""initial schema

Revision ID: a854f69c5fba
Revises: 
Create Date: 2026-09-30 22:05:14.751497

"""
from alembic import op
import sqlalchemy as sa

import api.models  # custom column types, e.g. api.models.UTCDateTime


# revision identifiers, used by Alembic.
revision = 'a854f69c5fba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('organization',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('pretty_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rate_limit',
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('key_hash')
    )
    with op.batch_alter_table('rate_limit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rate_limit_expires_at'), ['expires_at'], unique=False)

    op.create_table('event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('pretty_name', sa.String(length=255), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_event_organization_name')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_organization_id'), ['organization_id'], unique=False)

    op.create_table('user_organization',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_user_organization_user_org')
    )
    with op.batch_alter_table('user_organization', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_organization_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_organization_user_id'), ['user_id'], unique=False)

    op.create_table('enrichment_type',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('volunteer_interaction', sa.Enum('multiselect', 'select', name='volunteer_interaction', create_constraint=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enrichment_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrichment_type_event_id'), ['event_id'], unique=False)

    op.create_table('volunteer_offer',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), server_default='', nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('created_on', api.models.UTCDateTime(), nullable=False),
    sa.Column('updated_on', api.models.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'email', name='uq_volunteer_offer_event_email')
    )
    with op.batch_alter_table('volunteer_offer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_volunteer_offer_event_id'), ['event_id'], unique=False)

    op.create_table('volunteer_window',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('start', api.models.UTCDateTime(), nullable=False),
    sa.Column('end', api.models.UTCDateTime(), nullable=False),
    sa.CheckConstraint('start <= "end"', name='ck_volunteer_window_start_before_end'),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('volunteer_window', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_volunteer_window_event_id'), ['event_id'], unique=False)

    op.create_table('enrichment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enrichment_type_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['enrichment_type_id'], ['enrichment_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enrichment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrichment_enrichment_type_id'), ['enrichment_type_id'], unique=False)

    op.create_table('enrichment_fragment_type',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hidden', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('enrichment_type_id', sa.Uuid(), nullable=False),
    sa.Column('fragment_type', sa.Enum('text', 'calendar', name='fragment_type', create_constraint=True), nullable=False),
    sa.ForeignKeyConstraint(['enrichment_type_id'], ['enrichment_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enrichment_fragment_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrichment_fragment_type_enrichment_type_id'), ['enrichment_type_id'], unique=False)

    op.create_table('volunteer_window_offer',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('volunteer_offer_id', sa.Uuid(), nullable=False),
    sa.Column('volunteer_window_id', sa.Uuid(), nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=False),
    sa.Column('sequence', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cancelled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['volunteer_offer_id'], ['volunteer_offer.id'], ),
    sa.ForeignKeyConstraint(['volunteer_window_id'], ['volunteer_window.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid'),
    sa.UniqueConstraint('volunteer_offer_id', 'volunteer_window_id', name='uq_volunteer_window_offer_offer_window')
    )
    with op.batch_alter_table('volunteer_window_offer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_volunteer_window_offer_volunteer_offer_id'), ['volunteer_offer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_volunteer_window_offer_volunteer_window_id'), ['volunteer_window_id'], unique=False)

    op.create_table('calendar_enrichment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enrichment_id', sa.Uuid(), nullable=False),
    sa.Column('enrichment_fragment_type_id', sa.Uuid(), nullable=False),
    sa.Column('start', api.models.UTCDateTime(), nullable=False),
    sa.Column('end', api.models.UTCDateTime(), nullable=False),
    sa.CheckConstraint('start <= "end"', name='ck_calendar_enrichment_start_before_end'),
    sa.ForeignKeyConstraint(['enrichment_fragment_type_id'], ['enrichment_fragment_type.id'], ),
    sa.ForeignKeyConstraint(['enrichment_id'], ['enrichment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_enrichment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_enrichment_enrichment_fragment_type_id'), ['enrichment_fragment_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_enrichment_enrichment_id'), ['enrichment_id'], unique=False)

    op.create_table('text_enrichment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enrichment_id', sa.Uuid(), nullable=False),
    sa.Column('enrichment_fragment_type_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['enrichment_fragment_type_id'], ['enrichment_fragment_type.id'], ),
    sa.ForeignKeyConstraint(['enrichment_id'], ['enrichment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('text_enrichment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_text_enrichment_enrichment_fragment_type_id'), ['enrichment_fragment_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_text_enrichment_enrichment_id'), ['enrichment_id'], unique=False)

    op.create_table('volunteer_offer_enrichment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('volunteer_offer_id', sa.Uuid(), nullable=False),
    sa.Column('enrichment_id', sa.Uuid(), nullable=False),
    sa.Column('created_on', api.models.UTCDateTime(), nullable=False),
    sa.Column('updated_on', api.models.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enrichment_id'], ['enrichment.id'], ),
    sa.ForeignKeyConstraint(['volunteer_offer_id'], ['volunteer_offer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('volunteer_offer_id', 'enrichment_id', name='uq_volunteer_offer_enrichment_offer_enrichment')
    )
    with op.batch_alter_table('volunteer_offer_enrichment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_volunteer_offer_enrichment_enrichment_id'), ['enrichment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_volunteer_offer_enrichment_volunteer_offer_id'), ['volunteer_offer_id'], unique=False)

    op.create_table('volunteer_offer_response',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('volunteer_window_offer_id', sa.Uuid(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('created_on', api.models.UTCDateTime(), nullable=False),
    sa.Column('updated_on', api.models.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['volunteer_window_offer_id'], ['volunteer_window_offer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('volunteer_window_offer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volunteer_offer_response')
    with op.batch_alter_table('volunteer_offer_enrichment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_volunteer_offer_enrichment_volunteer_offer_id'))
        batch_op.drop_index(batch_op.f('ix_volunteer_offer_enrichment_enrichment_id'))

    op.drop_table('volunteer_offer_enrichment')
    with op.batch_alter_table('text_enrichment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_text_enrichment_enrichment_id'))
        batch_op.drop_index(batch_op.f('ix_text_enrichment_enrichment_fragment_type_id'))

    op.drop_table('text_enrichment')
    with op.batch_alter_table('calendar_enrichment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_enrichment_enrichment_id'))
        batch_op.drop_index(batch_op.f('ix_calendar_enrichment_enrichment_fragment_type_id'))

    op.drop_table('calendar_enrichment')
    with op.batch_alter_table('volunteer_window_offer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_volunteer_window_offer_volunteer_window_id'))
        batch_op.drop_index(batch_op.f('ix_volunteer_window_offer_volunteer_offer_id'))

    op.drop_table('volunteer_window_offer')
    with op.batch_alter_table('enrichment_fragment_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrichment_fragment_type_enrichment_type_id'))

    op.drop_table('enrichment_fragment_type')
    with op.batch_alter_table('enrichment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrichment_enrichment_type_id'))

    op.drop_table('enrichment')
    with op.batch_alter_table('volunteer_window', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_volunteer_window_event_id'))

    op.drop_table('volunteer_window')
    with op.batch_alter_table('volunteer_offer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_volunteer_offer_event_id'))

    op.drop_table('volunteer_offer')
    with op.batch_alter_table('enrichment_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrichment_type_event_id'))

    op.drop_table('enrichment_type')
    with op.batch_alter_table('user_organization', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_organization_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_organization_organization_id'))

    op.drop_table('user_organization')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_organization_id'))

    op.drop_table('event')
    with op.batch_alter_table('rate_limit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rate_limit_expires_at'))

    op.drop_table('rate_limit')
    op.drop_table('organization')
    op.drop_table('app_user')
    # ### end Alembic commands ###
    # Enum types outlive their tables on Postgres (no-op elsewhere).
    sa.Enum(name='fragment_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='volunteer_interaction').drop(op.get_bind(), checkfirst=True)
